### ISSUE TITLE
Error in parsing PGN

### ISSUE THREAD

**Issue by kevinpolisano** [chrislicodes/obsidian-chess-study#2]
Hello,

Thank you for this great plugin!

I tried to import this PGN (which works on lichess):

```pgn
[FEN "r1bqkbnr/1pp2ppp/p1p5/4p3/3PP3/5N2/PPP2PPP/RNBQK2R b KQkq - 0 5"]
5... Bg4
```

and I get this error:

```bash
plugin:chess-study:45863 Error: Invalid move in PGN: [FEN
    at Chess.loadPgn (plugin:chess-study:25237:17)
    at PgnModal.onSubmit (plugin:chess-study:45838:21)
    at eval (plugin:chess-study:45769:14)
    at HTMLButtonElement.<anonymous> (app.js:1:820048)
```

**Edit**: I have noticed that starting from a given FEN is in your TODO list, sorry!

Best regards

**Comment by chrislicodes** [comment]
Hey,

interesting - which tool is exporting PGNs like this? Is it also on LiChess? PGNs are parsed with https://github.com/jhlywa/chess.js - so we could sanitise the string additionally, but for now it would be best to remove the FEN string.

**Comment by kevinpolisano** [comment]
Hey,

It is the common notation for games/problems starting at a given position. Indeed you can load or export that on Lichess.

This tool also takes advantage to that notation to produce Anki flashcard: https://github.com/TowelSniffer/Anki-Chess-2.0

**Comment by chrislicodes** [comment]
Hey Kevin, there will be a new version soon which will support FEN starting positions - there is no plan to support the string you posted right now but feel free to submit a PR! 🤖

**Comment by kevinpolisano** [comment]
Hey Chris!

Can you explain how to declare a FEN starting position? :)

**Comment by kevinpolisano** [comment]
Can you explain how to declare a FEN starting position? :)
