### ISSUE TITLE
[Feature Request] Start Position FEN

### ISSUE THREAD

**Issue by BDubbB** [chrislicodes/obsidian-chess-study#7]
Hi,

I would like to use this to study my Chess Steps books, but I need to be able to input tons of positions very fast. Do you think FEN starting positions will be added any time soon?

**Comment by latenitecoding** [comment]
We're still polishing, but this feature is now included in the plugin. This issue can likely be closed.

**Comment by latenitecoding** [comment]
This feature has been included in the plugin. I think we can close this issue.

**Comment by chrislicodes** [comment]
A new version will be released soon with support for FEN strings 🎊
